<?php

function hints()
{
    
    $hint=array();
    if (($handle = fopen("http://". $_SERVER['HTTP_HOST'] ."/hints.csv", "r")) !== FALSE) {
    	$row = 0;
    	while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
    		$num = count($data);
    		$row++;
    		$hint[]=$data[0];
    	}
    	fclose($handle);
    }
    $rn=rand(1,$row);
    echo $hint[$rn];
    
}

if(isset($_GET['first_name']))
{
    echo '
    <script type="text/javascript">
    setTimeout("beginrefresh()",10000);
    
    function beginrefresh(){
    	// window.location.reload();
    	window.location.href = "?first_name='.urlencode($_GET['first_name']).'&last_name='.urlencode($_GET['last_name']).'";
    }
    
    </script>';
	echo '<H2>Willkommen '.$_GET['first_name'].' '.$_GET['last_name'].' !</H2>';
	
    hints();	
    
}
else
{
if($this->login)
{
    echo '
    <script type="text/javascript">
    setTimeout("beginrefresh()",10000);
    
    function beginrefresh(){
    	// window.location.reload();
    	window.location.href = "?first_name='.urlencode($this->first_name).'&last_name='.urlencode($this->last_name).'";
    }
    
    </script>';
    
    echo '<H2>Willkommen '.$this->first_name.' '.$this->last_name.' !</H2>';
    
    hints();
}
else 
{
    echo '<H2>Username und/oder Passwort falsch!</H2><BR>';
    echo '<div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="'. $this->url('home') .'">'.$this->translate('Zum Login').' </a></li>
                        </ul>
                    </div><!--/.nav-collapse -->';
}    
}
?>